plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - _pages

exclude:
  - .cpanel.yml
  - deploy
  - README.md

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.

collections:
  projects:
    output: true
    permalink: /projects/:path/
